[package]
name = "vrc-log"
version = "0.5.8"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"
description = "VRChat Local Cache Avatar ID Logger"
readme = "README.md"
homepage = "https://git.shaybox.com/vrc-log/releases/latest"
repository = "https://github.com/ShayBox/VRC-LOG"
license = "MIT"
keywords = ["vrchat", "local", "cache", "avatar", "logger"]
categories = ["config", "database", "filesystem", "games", "parsing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = "0.4.32"
colored = "2"
crossbeam = "0.8"
crossterm = { version = "0.27", optional = true }
discord-presence = { version = "1", optional = true }
indexmap = "2"
lazy_static = "1"
notify = "6"
parking_lot = "0.12"
regex = "1"
reqwest = { version = "0.12", features = ["blocking", "json"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlite = { version = "0.36", features = ["bundled"], optional = true }
strum = { version = "0.26", features = ["derive"] }
terminal-link = "0.1"

[features]
default = ["cache", "sqlite", "title", "vrcdb", "nekodb"]
cache = []
discord = ["dep:discord-presence"]
sqlite = ["dep:sqlite"]
title = ["dep:crossterm"]
vrcdb = ["dep:reqwest", "discord"]
nekodb = ["dep:reqwest", "discord"]

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"
